import type { Metadata } from "next";
import Link from "next/link";
import { ExternalLink, links } from "@/components/site-shell";

export const metadata: Metadata = { title: "Invoice Dashboard Example" };

export default function InvoiceDashboardExample() {
  return <><section className="page-hero"><div className="container"><p className="eyebrow">Post-deploy integration</p><h1>Put the Arc agent<br />inside your app.</h1><p className="lede">The included dashboard routes directly to a deployed Aomi Application ID, exposes the fixture invoice API, and keeps Circle review beside the conversation.</p><div className="status-banner"><strong>Application ID required for live chat.</strong> The local invoice decisions work without credentials; the hosted agent panel activates only after Aomi Build returns an Application ID.</div></div></section><section className="section"><div className="container content-grid"><div><p className="eyebrow">Return from Aomi Build</p><h2>Three settings connect the finished system.</h2></div><div className="steps"><div className="step"><strong>1. Point the agent at the app</strong>Set <code>INVOICE_API_BASE_URL</code> to the dashboard&apos;s HTTPS <code>/api</code> origin.</div><div className="step"><strong>2. Route the dashboard</strong>Set <code>NEXT_PUBLIC_AOMI_APPLICATION_ID</code> and the documented Aomi backend URL.</div><div className="step"><strong>3. Keep signing private</strong>Run the Circle reference signer only on loopback. Put the shared adapter behind your authenticated backend in a real app.</div><div className="actions"><ExternalLink className="button primary" href={links.invoiceDashboard}>Open dashboard source ↗</ExternalLink><ExternalLink className="button" href={links.build}>Open Aomi Build ↗</ExternalLink><Link className="button" href="/proof/pay-the-right-invoice">Review the proof</Link></div></div></div></section></>;
}
